### ISSUE TITLE
Service tracking issue for GSP-127: Add ServiceInternel and RequestThrottled Errors

### ISSUE THREAD

**Issue by Xuanwo** [beyondstorage/go-service-ipfs#10]
- [Rendered GSP](https://github.com/beyondstorage/go-storage/blob/master/docs/rfcs/127-add-serviceinternel-and-requestthrottled-errors.md)
- [Tracking Issue](https://github.com/beyondstorage/go-storage/issues/612)

> This is the service tracking issue that generated by go-community, please close with comments if not applicable to this project.

## Steps

- [ ] Update `formatError` to add new errors check

**Comment by zu1k** [comment]
Has been completed.

https://github.com/beyondstorage/go-service-ipfs/blob/37376f2dcd4c2c4170ec098b13e76c29c4352420/utils.go#L90-L96
