### ISSUE TITLE
Should implement `Reacher`?

### ISSUE THREAD

**Issue by zu1k** [beyondstorage/go-service-ipfs#5]
Should I implement `Reacher`?

With IPFS, I can get the `CID` of an object, then I can use it with a public or internal `IPFS Gateway` to splice out the access link.

When using internal gateway like `127.0.0.1:8080`, the access link are inaccessible from external network.
I can use a public gateway, e.g., `ipfs.io`, `cf-ipfs.com`. 
However, if the service is an intranet IPFS cluster, it is possible that the files are not accessible from these public gateway as well.

I could try adding a pair to let the user specify the gateway, but I think that would add complexity.

_Originally posted by @zu1k in https://github.com/beyondstorage/go-service-ipfs/pull/3#issuecomment-872002230_

**Comment by Xuanwo** [comment]
> I could try adding a pair to let the user specify the gateway, but I think that would add complexity.

Makes sense to me, how about start an RFC for ipfs (in this repo instead go-storage) for deep discussion?

**Comment by zu1k** [comment]
Is there any RFC example?

**Comment by Xuanwo** [comment]
We can use the format from `go-storage`: https://github.com/beyondstorage/go-storage/blob/master/docs/rfcs/0-example.md

And take `beyond-fs`'s first RFC as example: https://github.com/beyondstorage/beyond-fs/pull/5

<blockquote><img src="https://opengraph.githubassets.com/dbd8cd6841628658759a2de19925f43a41e8b5a2f91c7de2387167f04638b790/beyondstorage/go-storage" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/beyondstorage/go-storage">beyondstorage/go-storage</a></strong></div><div>A vendor-neutral storage library for Golang: Write once, run on every storage service. - beyondstorage/go-storage</div></blockquote>

**Comment by JinnyYi** [comment]
Hi @zu1k, `Reacher` has been deprecated. Maybe `QuerySignHTTPRead` could be an alternative?
ref: https://forum.beyondstorage.io/t/topic/222

<blockquote><img src="https://aos-forum.s3.gd2.qingstor.com/original/1X/c20e7258af8443fa28b26c88e7131f6f6b4eddb7.png" width="48" align="right"><div><img src="https://aos-forum.s3.gd2.qingstor.com/optimized/1X/adf1e8fa8e251d6262c51785d3f66df9e93486c5_2_32x32.png" height="14"> BeyondStorage</div><div><strong><a href="https://forum.beyondstorage.io/t/topic/222">Migrate Reach to QuerySignHTTPRead</a></strong></div><div>Introduction  Reach Reacher is used to get a public accessible url to object.   QuerySignHTTPRead StorageHTTPSigner is used to generate HTTP requests with signature information for storage service. QuerySignHTTPRead will read data from the file by using query parameters to authenticate requests.  For *http.Request returned by QuerySignHttpRead, where the URL field specifies either the URI being requested (for server requests) or the URL to access (for client requests) with signature in the quer...</div></blockquote>
